### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by blendaddict** [theGrue/jeopardy#6]
When I try to compile it outputs me this:
```
/home/simon/Documents/jeopardy/app.js:19
var io = require('socket.io').listen(server);
                              ^

TypeError: require(...).listen is not a function
    at Object.<anonymous> (/home/simon/Documents/jeopardy/app.js:19:31)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

```
even though npm and bower are installed

**Comment by theGrue** [comment]
Sorry, I'm not able to reproduce this! What version of Node (`node --version`) are you using?

**Comment by benmatz** [comment]
@theGrue I am also having a very similar issue where it outputs this when I do `node app.js`
```
/Users/ben/Downloads/jeopardy/app.js:19
var io = require('socket.io').listen(server);
                              ^

TypeError: require(...).listen is not a function
    at Object.<anonymous> (/Users/ben/Downloads/jeopardy/app.js:19:31)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47
```
I have v14.17.3 FYI. Thanks!

**Comment by theGrue** [comment]
I'm still not able to reproduce this. Can you tell me what gets output when you run `npm ls socket.io` ?

**Comment by benmatz** [comment]
I got this `/Users/ben
└── (empty)
`

**Comment by theGrue** [comment]
Sorry, I should have been more specific. Please run that command in the same folder as the project (looks like `/Users/ben/Downloads/jeopardy`).

**Comment by benmatz** [comment]
[
<img width="523" alt="Screen Shot 2021-07-30 at 5 28 07 PM" src="https://user-images.githubusercontent.com/88126990/127713266-f09ae21b-caa1-451b-8186-0628cdac986a.png">
](url)

**Comment by theGrue** [comment]
That's what I was afraid of! The package.json file calls for `"socket.io": "~1.3.6"`, which is a much older version than you have right now.

You could try `npm install socket.io@1.3.6` and see what happens, but I'm very confused how npm could have installed such an incorrect version for you.

**Comment by benmatz** [comment]
I now have the proper version of socket, but then it told me I needed jade so I ran `npm install jade` which seemed to work (it said it's installed but I did get some error messages when installing it) and when I then ran `node app.js`, I got the message `Express server listening on port 3000`. But, when I clicked on the two links in steps 5 and 6 of running the app, I got blank screens and this is what my terminal says 
```
Express server listening on port 3000
GET / 304 150.219 ms - -
GET /bower_components/bootstrap/dist/css/bootstrap.css 304 25.369 ms - -
GET /css/app.css 304 25.641 ms - -
GET /bower_components/angular-socket-io/socket.js 304 16.973 ms - -
GET /bower_components/angular/angular.js 304 32.117 ms - -
GET /js/app.js 304 32.149 ms - -
GET /bower_components/angular-ui-router/release/angular-ui-router.js 304 44.776 ms - -
GET /bower_components/angular-bootstrap/ui-bootstrap-tpls.js 304 23.090 ms - -
GET /bower_components/angular-sanitize/angular-sanitize.js 304 34.252 ms - -
GET /js/controllers/board.js 304 34.488 ms - -
GET /js/services.js 304 1.380 ms - -
GET /js/controllers.js 304 1.337 ms - -
GET /js/filters.js 304 1.443 ms - -
GET /js/controllers/boardclue.js 304 1.667 ms - -
GET /js/controllers/game.js 304 1.512 ms - -
GET /js/controllers/gameclue.js 304 1.525 ms - -
GET /js/directives.js 304 0.326 ms - -
GET /favicon.ico 304 7.796 ms - -
GET / 304 20.822 ms - -
GET /bower_components/bootstrap/dist/css/bootstrap.css 304 22.816 ms - -
GET /css/app.css 304 22.300 ms - -
GET /bower_components/angular-socket-io/socket.js 304 17.729 ms - -
GET /bower_components/angular/angular.js 304 28.887 ms - -
GET /js/app.js 304 28.794 ms - -
GET /bower_components/angular-ui-router/release/angular-ui-router.js 304 42.690 ms - -
GET /bower_components/angular-bootstrap/ui-bootstrap-tpls.js 304 12.718 ms - -
GET /bower_components/angular-sanitize/angular-sanitize.js 304 24.858 ms - -
GET /js/controllers/board.js 304 24.801 ms - -
GET /js/controllers/boardclue.js 304 26.885 ms - -
GET /js/services.js 304 2.471 ms - -
GET /js/controllers.js 304 2.600 ms - -
GET /js/filters.js 304 2.416 ms - -
GET /js/controllers/game.js 304 0.884 ms - -
GET /js/controllers/gameclue.js 304 0.927 ms - -
GET /js/directives.js 304 0.472 ms - -
GET /favicon.ico 304 6.392 ms - -
```

Btw, I realized that it's entirely possible that this app doesn't work on a Mac, which I have. Thanks for all your help!

**Comment by theGrue** [comment]
I have only ever run it on a Mac, so it definitely does!

Everything in the output you posted looks pretty normal. Does your web browser's console show any errors that could explain the blank screen?

**Comment by benmatz** [comment]
Nope, both pages look like this
<img width="1415" alt="Screen Shot 2021-08-02 at 12 27 30 PM" src="https://user-images.githubusercontent.com/88126990/127893716-bbdf14a7-36f3-4ab4-ae55-aefc4f58c796.png">
and awesome, I'm really excited to run this when it finally works!

**Comment by theGrue** [comment]
I don't see a browser console open there, can you check if that has any errors in it? Here's a guide to how to get to it: https://balsamiq.com/support/faqs/browserconsole/#google-chrome (or tl;dr: Option + ⌘ + J)

I'm not totally positive, but you may need to open the console first then refresh the blank page before errors will show up.

**Comment by benmatz** [comment]
Yup, both pages have the same errors.
<img width="553" alt="Screen Shot 2021-08-02 at 6 43 09 PM" src="https://user-images.githubusercontent.com/88126990/127932733-f1676150-be49-48b7-87d7-7c9a24816121.png">
If you can't tell, I'm pretty inexperienced in this area of computers so thank you for bearing with me!

**Comment by theGrue** [comment]
Gotcha, it looks like Bower didn't do its job and download the front-end dependencies... What happens when you run `bower install`?

**Comment by benmatz** [comment]
I get this message `zsh: command not found: bower`

**Comment by theGrue** [comment]
Well let's get that installed then! `npm install -g bower`

**Comment by benmatz** [comment]
Oh boy, I got a whole lot of errors this time around (which must've happened the first time around too because I thought I'd already installed it).
<img width="555" alt="Screen Shot 2021-08-02 at 11 12 39 PM" src="https://user-images.githubusercontent.com/88126990/127951864-2fda226a-5842-4ed0-a165-3390e32a90fb.png">

**Comment by theGrue** [comment]
Here's the top answer on StackOverflow for that issue: https://stackoverflow.com/a/51024493

**Comment by benmatz** [comment]
I'm very close now! I'm able to pull up both tabs and select a season. However, when I go to select a game, I get this error message
<img width="1009" alt="Screen Shot 2021-08-03 at 11 51 33 AM" src="https://user-images.githubusercontent.com/88126990/128047718-ae16fae3-e85f-49e9-9cf9-4a73b5cba8ec.png">
and in my browser console I see just this one error
<img width="544" alt="Screen Shot 2021-08-03 at 11 54 47 AM" src="https://user-images.githubusercontent.com/88126990/128047804-7a129b80-d979-494a-89d5-f0998533921a.png">

**Comment by theGrue** [comment]
This is another case where you've ended up with a package that's newer than the one required, that has since deprecated a function I'm using here. I'm really baffled as to why npm would be giving you these versions... Can you try a `rm -rf node_modules package-lock.json && npm install` and see if it does any better a second time?

**Comment by benmatz** [comment]
When I ran that command it gave me all of this and I had the same error when I tried to run it again. Would it possibly be worth it to uninstall everything and start from scratch?
<img width="1192" alt="Screen Shot 2021-08-03 at 12 05 43 PM" src="https://user-images.githubusercontent.com/88126990/128049132-99adc7ae-c3ce-48e4-9bf8-37dab5dce941.png">

**Comment by theGrue** [comment]
Hmm, that's pretty much what we just did (uninstall everything and start from scratch). Everything in your screenshot seems pretty normal... Can you post the output of `npm ls`? I want to see if you ended up with the wrong versions of some of the packages again.

**Comment by benmatz** [comment]
```
├─┬ body-parser@1.19.0
│ ├── bytes@3.1.0
│ ├── content-type@1.0.4
│ ├─┬ debug@2.6.9
│ │ └── ms@2.0.0
│ ├── depd@1.1.2
│ ├─┬ http-errors@1.7.2
│ │ ├── depd@1.1.2 deduped
│ │ ├── inherits@2.0.3
│ │ ├── setprototypeof@1.1.1 deduped
│ │ ├── statuses@1.5.0 deduped
│ │ └── toidentifier@1.0.0
│ ├─┬ iconv-lite@0.4.24
│ │ └── safer-buffer@2.1.2
│ ├─┬ on-finished@2.3.0
│ │ └── ee-first@1.1.1
│ ├── qs@6.7.0
│ ├─┬ raw-body@2.4.0
│ │ ├── bytes@3.1.0 deduped
│ │ ├── http-errors@1.7.2 deduped
│ │ ├── iconv-lite@0.4.24 deduped
│ │ └── unpipe@1.0.0
│ └─┬ type-is@1.6.18
│   ├── media-typer@0.3.0
│   └── mime-types@2.1.32 deduped
├── bower@1.8.12
├─┬ cheerio@0.22.0
│ ├─┬ css-select@1.2.0
│ │ ├── boolbase@1.0.0
│ │ ├── css-what@2.1.3
│ │ ├─┬ domutils@1.5.1
│ │ │ ├── dom-serializer@0.1.1 deduped
│ │ │ └── domelementtype@1.3.1 deduped
│ │ └─┬ nth-check@1.0.2
│ │   └── boolbase@1.0.0 deduped
│ ├─┬ dom-serializer@0.1.1
│ │ ├── domelementtype@1.3.1
│ │ └── entities@1.1.2 deduped
│ ├── entities@1.1.2
│ ├─┬ htmlparser2@3.10.1
│ │ ├── domelementtype@1.3.1 deduped
│ │ ├─┬ domhandler@2.4.2
│ │ │ └── domelementtype@1.3.1 deduped
│ │ ├── domutils@1.5.1 deduped
│ │ ├── entities@1.1.2 deduped
│ │ ├── inherits@2.0.3 deduped
│ │ └─┬ readable-stream@3.6.0
│ │   ├── inherits@2.0.3 deduped
│ │   ├─┬ string_decoder@1.3.0
│ │   │ └── safe-buffer@5.2.1 deduped
│ │   └── util-deprecate@1.0.2
│ ├── lodash.assignin@4.2.0
│ ├── lodash.bind@4.2.1
│ ├── lodash.defaults@4.2.0
│ ├── lodash.filter@4.6.0
│ ├── lodash.flatten@4.4.0
│ ├── lodash.foreach@4.5.0
│ ├── lodash.map@4.6.0
│ ├── lodash.merge@4.6.2
│ ├── lodash.pick@4.4.0
│ ├── lodash.reduce@4.6.0
│ ├── lodash.reject@4.6.0
│ └── lodash.some@4.6.0
├─┬ errorhandler@1.5.1
│ ├─┬ accepts@1.3.7
│ │ ├── mime-types@2.1.32 deduped
│ │ └── negotiator@0.6.2
│ └── escape-html@1.0.3
├─┬ express@4.17.1
│ ├── accepts@1.3.7 deduped
│ ├── array-flatten@1.1.1
│ ├── body-parser@1.19.0 deduped
│ ├─┬ content-disposition@0.5.3
│ │ └── safe-buffer@5.1.2
│ ├── content-type@1.0.4 deduped
│ ├── cookie@0.4.0
│ ├── cookie-signature@1.0.6
│ ├── debug@2.6.9 deduped
│ ├── depd@1.1.2 deduped
│ ├── encodeurl@1.0.2
│ ├── escape-html@1.0.3 deduped
│ ├── etag@1.8.1
│ ├─┬ finalhandler@1.1.2
│ │ ├── debug@2.6.9 deduped
│ │ ├── encodeurl@1.0.2 deduped
│ │ ├── escape-html@1.0.3 deduped
│ │ ├── on-finished@2.3.0 deduped
│ │ ├── parseurl@1.3.3 deduped
│ │ ├── statuses@1.5.0 deduped
│ │ └── unpipe@1.0.0 deduped
│ ├── fresh@0.5.2
│ ├── merge-descriptors@1.0.1
│ ├── methods@1.1.2
│ ├── on-finished@2.3.0 deduped
│ ├── parseurl@1.3.3
│ ├── path-to-regexp@0.1.7
│ ├─┬ proxy-addr@2.0.7
│ │ ├── forwarded@0.2.0
│ │ └── ipaddr.js@1.9.1
│ ├── qs@6.7.0 deduped
│ ├── range-parser@1.2.1
│ ├── safe-buffer@5.1.2
│ ├─┬ send@0.17.1
│ │ ├── debug@2.6.9 deduped
│ │ ├── depd@1.1.2 deduped
│ │ ├── destroy@1.0.4
│ │ ├── encodeurl@1.0.2 deduped
│ │ ├── escape-html@1.0.3 deduped
│ │ ├── etag@1.8.1 deduped
│ │ ├── fresh@0.5.2 deduped
│ │ ├── http-errors@1.7.2 deduped
│ │ ├── mime@1.6.0
│ │ ├── ms@2.1.1
│ │ ├── on-finished@2.3.0 deduped
│ │ ├── range-parser@1.2.1 deduped
│ │ └── statuses@1.5.0 deduped
│ ├─┬ serve-static@1.14.1
│ │ ├── encodeurl@1.0.2 deduped
│ │ ├── escape-html@1.0.3 deduped
│ │ ├── parseurl@1.3.3 deduped
│ │ └── send@0.17.1 deduped
│ ├── setprototypeof@1.1.1
│ ├── statuses@1.5.0
│ ├── type-is@1.6.18 deduped
│ ├── utils-merge@1.0.1
│ └── vary@1.1.2
├─┬ http-proxy@1.18.1
│ ├── eventemitter3@4.0.7
│ ├── follow-redirects@1.14.1
│ └── requires-port@1.0.0
├─┬ jade@1.11.0
│ ├── character-parser@1.2.1
│ ├─┬ clean-css@3.4.28
│ │ ├─┬ commander@2.8.1
│ │ │ └── graceful-readlink@1.0.1
│ │ └─┬ source-map@0.4.4
│ │   └── amdefine@1.0.1
│ ├── commander@2.6.0
│ ├─┬ constantinople@3.0.2
│ │ └── acorn@2.7.0
│ ├─┬ jstransformer@0.0.2
│ │ ├── is-promise@2.2.2
│ │ └─┬ promise@6.1.0
│ │   └── asap@1.0.0
│ ├─┬ mkdirp@0.5.5
│ │ └── minimist@1.2.5
│ ├─┬ transformers@2.1.0
│ │ ├─┬ css@1.0.8
│ │ │ ├── css-parse@1.0.4
│ │ │ └── css-stringify@1.0.5
│ │ ├─┬ promise@2.0.0
│ │ │ └── is-promise@1.0.1
│ │ └─┬ uglify-js@2.2.5
│ │   ├─┬ optimist@0.3.7
│ │   │ └── wordwrap@0.0.3
│ │   └─┬ source-map@0.1.43
│ │     └── amdefine@1.0.1 deduped
│ ├─┬ uglify-js@2.8.29
│ │ ├── source-map@0.5.7
│ │ ├── uglify-to-browserify@1.0.2
│ │ └─┬ yargs@3.10.0
│ │   ├── camelcase@1.2.1
│ │   ├─┬ cliui@2.1.0
│ │   │ ├─┬ center-align@0.1.3
│ │   │ │ ├─┬ align-text@0.1.4
│ │   │ │ │ ├─┬ kind-of@3.2.2
│ │   │ │ │ │ └── is-buffer@1.1.6
│ │   │ │ │ ├── longest@1.0.1
│ │   │ │ │ └── repeat-string@1.6.1
│ │   │ │ └── lazy-cache@1.0.4
│ │   │ ├─┬ right-align@0.1.3
│ │   │ │ └── align-text@0.1.4 deduped
│ │   │ └── wordwrap@0.0.2
│ │   ├── decamelize@1.2.0
│ │   └── window-size@0.1.0
│ ├── void-elements@2.0.1
│ └─┬ with@4.0.3
│   ├── acorn@1.2.2
│   └─┬ acorn-globals@1.0.9
│     └── acorn@2.7.0 deduped
├─┬ jsonfile@2.4.0
│ └── graceful-fs@4.2.6
├── lodash@4.17.21
├─┬ method-override@2.3.10
│ ├── debug@2.6.9 deduped
│ ├── methods@1.1.2 deduped
│ ├── parseurl@1.3.3 deduped
│ └── vary@1.1.2 deduped
├─┬ morgan@1.10.0
│ ├─┬ basic-auth@2.0.1
│ │ └── safe-buffer@5.1.2
│ ├── debug@2.6.9 deduped
│ ├── depd@2.0.0
│ ├── on-finished@2.3.0 deduped
│ └── on-headers@1.0.2
├─┬ pug@3.0.2
│ ├─┬ pug-code-gen@3.0.2
│ │ ├─┬ constantinople@4.0.1
│ │ │ ├── @babel/parser@7.14.9
│ │ │ └─┬ @babel/types@7.14.9
│ │ │   ├── @babel/helper-validator-identifier@7.14.9
│ │ │   └── to-fast-properties@2.0.0
│ │ ├── doctypes@1.1.0
│ │ ├── js-stringify@1.0.2
│ │ ├─┬ pug-attrs@3.0.0
│ │ │ ├─┬ constantinople@4.0.1
│ │ │ │ ├── @babel/parser@7.14.9 deduped
│ │ │ │ └── @babel/types@7.14.9 deduped
│ │ │ ├── js-stringify@1.0.2 deduped
│ │ │ └── pug-runtime@3.0.1 deduped
│ │ ├── pug-error@2.0.0
│ │ ├── pug-runtime@3.0.1 deduped
│ │ ├── void-elements@3.1.0
│ │ └─┬ with@7.0.2
│ │   ├── @babel/parser@7.14.9 deduped
│ │   ├── @babel/types@7.14.9 deduped
│ │   ├── assert-never@1.2.1
│ │   └─┬ babel-walk@3.0.0-canary-5
│ │     └── @babel/types@7.14.9 deduped
│ ├─┬ pug-filters@4.0.0
│ │ ├─┬ constantinople@4.0.1
│ │ │ ├── @babel/parser@7.14.9 deduped
│ │ │ └── @babel/types@7.14.9 deduped
│ │ ├─┬ jstransformer@1.0.0
│ │ │ ├── is-promise@2.2.2 deduped
│ │ │ └─┬ promise@7.3.1
│ │ │   └── asap@2.0.6
│ │ ├── pug-error@2.0.0 deduped
│ │ ├── pug-walk@2.0.0
│ │ └─┬ resolve@1.20.0
│ │   ├─┬ is-core-module@2.5.0
│ │   │ └─┬ has@1.0.3
│ │   │   └── function-bind@1.1.1
│ │   └── path-parse@1.0.7
│ ├─┬ pug-lexer@5.0.1
│ │ ├─┬ character-parser@2.2.0
│ │ │ └─┬ is-regex@1.1.3
│ │ │   ├─┬ call-bind@1.0.2
│ │ │   │ ├── function-bind@1.1.1 deduped
│ │ │   │ └─┬ get-intrinsic@1.1.1
│ │ │   │   ├── function-bind@1.1.1 deduped
│ │ │   │   ├── has@1.0.3 deduped
│ │ │   │   └── has-symbols@1.0.2 deduped
│ │ │   └── has-symbols@1.0.2
│ │ ├─┬ is-expression@4.0.0
│ │ │ ├── acorn@7.4.1
│ │ │ └── object-assign@4.1.1 deduped
│ │ └── pug-error@2.0.0 deduped
│ ├─┬ pug-linker@4.0.0
│ │ ├── pug-error@2.0.0 deduped
│ │ └── pug-walk@2.0.0 deduped
│ ├─┬ pug-load@3.0.0
│ │ ├── object-assign@4.1.1
│ │ └── pug-walk@2.0.0 deduped
│ ├─┬ pug-parser@6.0.0
│ │ ├── pug-error@2.0.0 deduped
│ │ └── token-stream@1.0.0
│ ├── pug-runtime@3.0.1
│ └─┬ pug-strip-comments@2.0.0
│   └── pug-error@2.0.0 deduped
├─┬ request@2.88.2
│ ├── aws-sign2@0.7.0
│ ├── aws4@1.11.0
│ ├── caseless@0.12.0
│ ├─┬ combined-stream@1.0.8
│ │ └── delayed-stream@1.0.0
│ ├── extend@3.0.2
│ ├── forever-agent@0.6.1
│ ├─┬ form-data@2.3.3
│ │ ├── asynckit@0.4.0
│ │ ├── combined-stream@1.0.8 deduped
│ │ └── mime-types@2.1.32 deduped
│ ├─┬ har-validator@5.1.5
│ │ ├─┬ ajv@6.12.6
│ │ │ ├── fast-deep-equal@3.1.3
│ │ │ ├── fast-json-stable-stringify@2.1.0
│ │ │ ├── json-schema-traverse@0.4.1
│ │ │ └─┬ uri-js@4.4.1
│ │ │   └── punycode@2.1.1 deduped
│ │ └── har-schema@2.0.0
│ ├─┬ http-signature@1.2.0
│ │ ├── assert-plus@1.0.0
│ │ ├─┬ jsprim@1.4.1
│ │ │ ├── assert-plus@1.0.0 deduped
│ │ │ ├── extsprintf@1.3.0
│ │ │ ├── json-schema@0.2.3
│ │ │ └─┬ verror@1.10.0
│ │ │   ├── assert-plus@1.0.0 deduped
│ │ │   ├── core-util-is@1.0.2
│ │ │   └── extsprintf@1.3.0 deduped
│ │ └─┬ sshpk@1.16.1
│ │   ├─┬ asn1@0.2.4
│ │   │ └── safer-buffer@2.1.2 deduped
│ │   ├── assert-plus@1.0.0 deduped
│ │   ├─┬ bcrypt-pbkdf@1.0.2
│ │   │ └── tweetnacl@0.14.5 deduped
│ │   ├─┬ dashdash@1.14.1
│ │   │ └── assert-plus@1.0.0 deduped
│ │   ├─┬ ecc-jsbn@0.1.2
│ │   │ ├── jsbn@0.1.1 deduped
│ │   │ └── safer-buffer@2.1.2 deduped
│ │   ├─┬ getpass@0.1.7
│ │   │ └── assert-plus@1.0.0 deduped
│ │   ├── jsbn@0.1.1
│ │   ├── safer-buffer@2.1.2 deduped
│ │   └── tweetnacl@0.14.5
│ ├── is-typedarray@1.0.0
│ ├── isstream@0.1.2
│ ├── json-stringify-safe@5.0.1
│ ├─┬ mime-types@2.1.32
│ │ └── mime-db@1.49.0
│ ├── oauth-sign@0.9.0
│ ├── performance-now@2.1.0
│ ├── qs@6.5.2
│ ├── safe-buffer@5.2.1
│ ├─┬ tough-cookie@2.5.0
│ │ ├── psl@1.8.0
│ │ └── punycode@2.1.1
│ ├─┬ tunnel-agent@0.6.0
│ │ └── safe-buffer@5.2.1 deduped
│ └── uuid@3.4.0
└─┬ socket.io@1.7.4
  ├─┬ debug@2.3.3
  │ └── ms@0.7.2
  ├─┬ engine.io@1.8.5
  │ ├─┬ accepts@1.3.3
  │ │ ├── mime-types@2.1.32 deduped
  │ │ └── negotiator@0.6.1
  │ ├── base64id@1.0.0
  │ ├── cookie@0.3.1
  │ ├─┬ debug@2.3.3
  │ │ └── ms@0.7.2
  │ ├─┬ engine.io-parser@1.3.2
  │ │ ├── after@0.8.2
  │ │ ├── arraybuffer.slice@0.0.6
  │ │ ├── base64-arraybuffer@0.1.5
  │ │ ├── blob@0.0.4
  │ │ ├── has-binary@0.1.7 deduped
  │ │ └── wtf-8@1.0.0
  │ └─┬ ws@1.1.5
  │   ├── options@0.0.6
  │   └── ultron@1.0.2
  ├─┬ has-binary@0.1.7
  │ └── isarray@0.0.1
  ├── object-assign@4.1.0
  ├─┬ socket.io-adapter@0.5.0
  │ ├─┬ debug@2.3.3
  │ │ └── ms@0.7.2
  │ └── socket.io-parser@2.3.1 deduped
  ├─┬ socket.io-client@1.7.4
  │ ├── backo2@1.0.2
  │ ├── component-bind@1.0.0
  │ ├── component-emitter@1.2.1
  │ ├─┬ debug@2.3.3
  │ │ └── ms@0.7.2
  │ ├─┬ engine.io-client@1.8.6
  │ │ ├── component-emitter@1.2.1
  │ │ ├── component-inherit@0.0.3
  │ │ ├─┬ debug@2.3.3
  │ │ │ └── ms@0.7.2
  │ │ ├── engine.io-parser@1.3.2 deduped
  │ │ ├── has-cors@1.1.0
  │ │ ├── indexof@0.0.1 deduped
  │ │ ├─┬ parsejson@0.0.3
  │ │ │ └── better-assert@1.0.2 deduped
  │ │ ├─┬ parseqs@0.0.5
  │ │ │ └── better-assert@1.0.2 deduped
  │ │ ├── parseuri@0.0.5 deduped
  │ │ ├── ws@1.1.5 deduped
  │ │ ├── xmlhttprequest-ssl@1.6.3
  │ │ └── yeast@0.1.2
  │ ├── has-binary@0.1.7 deduped
  │ ├── indexof@0.0.1
  │ ├── object-component@0.0.3
  │ ├─┬ parseuri@0.0.5
  │ │ └─┬ better-assert@1.0.2
  │ │   └── callsite@1.0.0
  │ ├── socket.io-parser@2.3.1 deduped
  │ └── to-array@0.1.4
  └─┬ socket.io-parser@2.3.1
    ├── component-emitter@1.1.2
    ├─┬ debug@2.2.0
    │ └── ms@0.7.1
    ├── isarray@0.0.1 deduped
    └── json3@3.3.2
```

**Comment by theGrue** [comment]
Whoa, that's a lot, sorry about that! Here's what I get when I run `npm ls`:

```
├── bindings@1.2.1 extraneous
├── body-parser@1.19.0
├── cheerio@0.19.0
├── errorhandler@1.5.1
├── express@4.13.4
├── http-proxy@1.18.1
├── jade@1.11.0
├── jsonfile@2.4.0
├── lodash@3.10.1
├── method-override@2.3.10
├── morgan@1.10.0
├── request@2.88.2
└── socket.io@1.3.7
```

A lot more concise! I'm not sure why yours goes so many more layers deep.

But at any rate, here's the differences I can see, and here's a command you can run that npm should hopefully listen to: `npm install cheerio@0.19.0 express@4.13.4 lodash@3.10.1 socket.io@1.3.7`

**Comment by benmatz** [comment]
It works!!!! THANK YOU SO MUCH for all of your help over the last few days...can't wait to use the app!
